-- Student Profile Database Setup 
-- Run this in Apache Derby SQL tool 
 
CREATE TABLE PROFILES ( 
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
    STUDENT_ID VARCHAR(50) UNIQUE NOT NULL, 
    NAME VARCHAR(100) NOT NULL, 
    NAME VARCHAR(100) NOT NULL, 
    EMAIL VARCHAR(100) NOT NULL, 
    HOBBIES VARCHAR(200), 
    INTRO LONG VARCHAR, 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
); 
